// <auto-generated />
using System;
using Dokument_AK.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dokument_AK.Migrations
{
    [DbContext(typeof(DokumentContext))]
    [Migration("20220219205301_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dokument_AK.Entities.DokumentEnt", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StatusDokID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.ToTable("DokumentEnt");

                    b.HasData(
                        new
                        {
                            DokumentID = new Guid("1794d8c7-6c5c-4725-9d92-d819bdc07773"),
                            Datum = new DateTime(2021, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenjaDokumenta = new DateTime(2021, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDokID = new Guid("2f530032-429e-4be7-b202-d800876d393d"),
                            ZavodniBroj = "15548/RS7"
                        },
                        new
                        {
                            DokumentID = new Guid("cfe84b37-bb6d-498d-a546-5dee8758ed1a"),
                            Datum = new DateTime(2019, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenjaDokumenta = new DateTime(2019, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDokID = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            ZavodniBroj = "17748/RS7"
                        });
                });

            modelBuilder.Entity("Dokument_AK.Entities.EksterniDokumentEnt", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Izmenjen")
                        .HasColumnType("bit");

                    b.HasKey("DokumentID");

                    b.ToTable("EksterniDokumentEnt");

                    b.HasData(
                        new
                        {
                            DokumentID = new Guid("cfe84b37-bb6d-498d-a546-5dee8758ed1a"),
                            Izmenjen = false
                        });
                });

            modelBuilder.Entity("Dokument_AK.Entities.InterniDokumentEnt", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Izmenjen")
                        .HasColumnType("bit");

                    b.HasKey("DokumentID");

                    b.ToTable("InterniDokumentEnt");

                    b.HasData(
                        new
                        {
                            DokumentID = new Guid("1794d8c7-6c5c-4725-9d92-d819bdc07773"),
                            Izmenjen = true
                        });
                });

            modelBuilder.Entity("Dokument_AK.Entities.StatusDokumentaEnt", b =>
                {
                    b.Property<Guid?>("StatusDokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Odbijen")
                        .HasColumnType("bit");

                    b.Property<bool>("Otvoren")
                        .HasColumnType("bit");

                    b.Property<bool>("Usvojen")
                        .HasColumnType("bit");

                    b.HasKey("StatusDokID");

                    b.ToTable("StatusDokumentaEnt");

                    b.HasData(
                        new
                        {
                            StatusDokID = new Guid("2f530032-429e-4be7-b202-d800876d393d"),
                            Odbijen = false,
                            Otvoren = false,
                            Usvojen = true
                        },
                        new
                        {
                            StatusDokID = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            Odbijen = false,
                            Otvoren = true,
                            Usvojen = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
