// <auto-generated />
namespace LicnostService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblLicnost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblLicnost));
        
        string IMigrationMetadata.Id
        {
            get { return "202202040016424_tblLicnost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
