// <auto-generated />
using System;
using Mesto.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mesto.Migrations
{
    [DbContext(typeof(MestoContext))]
    partial class MestoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mesto.Entities.Adresa", b =>
                {
                    b.Property<Guid>("AdresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresaId");

                    b.ToTable("Adresa");

                    b.HasData(
                        new
                        {
                            AdresaId = new Guid("814f8e70-0edf-4cf5-8729-5091f7590b68"),
                            Mesto = "SM",
                            PostanskiBroj = 2200,
                            Ulica = "SAve kovacevica 25"
                        });
                });

            modelBuilder.Entity("Mesto.Entities.Drzava", b =>
                {
                    b.Property<Guid>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzava");

                    b.HasData(
                        new
                        {
                            DrzavaId = new Guid("24742b99-32c6-4999-b0a7-757a178f9ee7"),
                            Naziv = "Srbija"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
